schema: "https://v1c0jmuai8.execute-api.us-east-1.amazonaws.com/dev/graphql"
documents: ./src/api/**/*.graphql
generates:
  ./src/api/resolvers-types.ts:
    plugins:
      - typescript
      - typescript-resolvers
