service: email-forwarder-api

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline

package:
  include:
    - src/api/schema.graphql

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get
