service: email-forwarder-api

provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

package:
  include:
    - src/api/schema/schema.graphql

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get

resources:
  Resources:
    auth:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auth
        AttributeDefinitions:
          - AttributeName: AuthToken
            AttributeType: S
        KeySchema:
          - AttributeName: AuthToken
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    user:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Username
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: Username
            KeySchema:
              - AttributeName: Username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    route:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: route
        AttributeDefinitions:
          - AttributeName: To
            AttributeType: S
        KeySchema:
          - AttributeName: To
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    verified-email:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: verified-email
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: Email
            KeySchema:
              - AttributeName: Email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
