service: email-forwarder-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  JWT_SECRET: ${file(jwt_secret.txt)}
  dynamodb:
    stages:
      - dev
    start:
      migrate: true

package:
  include:
    - src/api/schema/schema.graphql

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
    environment:
      JWT_SECRET: ${self:custom.JWT_SECRET}
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get

resources:
  Resources:
    authTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auth
        AttributeDefinitions:
          - AttributeName: AuthToken
            AttributeType: S
        KeySchema:
          - AttributeName: AuthToken
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Username
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: Username
            KeySchema:
              - AttributeName: Username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    routeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: route
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: EmailMaskID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: EmailMaskID
            KeySchema:
              - AttributeName: EmailMaskID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    verifiedEmailTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: verified-email
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: Email
            KeySchema:
              - AttributeName: Email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    emailMaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: email-mask
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: BaseWithDomain
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: BaseWithDomain
            KeySchema:
              - AttributeName: BaseWithDomain
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
