service: email-forwarder-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  stage: ${opt:stage}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action: "ses:SendEmail"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
      Resource: "arn:aws:s3:::email-forwarder-inbound-emails/*"
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:UpdateItem"
      Resource: "arn:aws:dynamodb:us-east-1:${self:custom.AWS_ACCOUNT.${self:provider.stage}}:table/*"

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

custom:
  JWT_SECRET: ${file(jwt_secret.txt)}
  WEB_APP_BASE_URL:
    local: http://localhost:4200
    dev: https://app.mailmasker-dev.com
    prod: https://app.mailmasker.com
  API_BASE_URL:
    local: http://localhost:4201
    dev: https://n0tccaeafe.execute-api.us-east-1.amazonaws.com/dev/graphql
    prod: https://5ezbjkpthf.execute-api.us-east-1.amazonaws.com/prod/graphql
  AWS_ACCOUNT:
    local: ""
    dev: 747558615165
    prod: 726929401065
  dynamodb:
    stages:
      - local
    start:
      migrate: true
      port: 8000
      inMemory: true

package:
  include:
    - src/api/schema/schema.graphql

functions:
  graphql:
    handler: index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
    environment:
      JWT_SECRET: ${self:custom.JWT_SECRET}
      WEB_APP_BASE_URL: ${self:custom.WEB_APP_BASE_URL.${self:provider.stage}}
      API_BASE_URL: ${self:custom.API_BASE_URL.${self:provider.stage}}
  playground:
    handler: index.handler
    events:
      - http:
          path: playground
          method: get

resources:
  Resources:
    authTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: auth
        AttributeDefinitions:
          - AttributeName: AuthToken
            AttributeType: S
        KeySchema:
          - AttributeName: AuthToken
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Username
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: Username
            KeySchema:
              - AttributeName: Username
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    routeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: route
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: EmailMaskID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: EmailMaskID
            KeySchema:
              - AttributeName: EmailMaskID
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    verifiedEmailTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: verified-email
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: Email
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: Email
            KeySchema:
              - AttributeName: Email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    emailMaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: email-mask
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: BaseWithDomain
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: BaseWithDomain
            KeySchema:
              - AttributeName: BaseWithDomain
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
